-- CRIANDO O BANCO 
CREATE DATABASE COMERCIO;

--CONECTANDO AO BANCO
USE COMERCIO;

-- CRIANDO TABELAS

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(50) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2),
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE),
    REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('COM', 'RES', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
);

-- INSERINDO DADOS NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M', 'JOAO@JOAO.COM', '1234567899');
INSERT INTO CLIENTE VALUES(NULL, 'MARIA', 'F', 'MARIA@MARIASILVA.COM', '569871032');
INSERT INTO CLIENTE VALUES(NULL, 'HENRIQUE', 'M', 'HENRIQUEDOIDO@SOMAISUM.COM', '486321569');
INSERT INTO CLIENTE VALUES(NULL, 'THIAGO', 'M', NULL, '623598419');
INSERT INTO CLIENTE VALUES(NULL, 'MELISSA', 'F', 'MELISSACONCEICAO@MELISSA.COM', '030312954');
INSERT INTO CLIENTE VALUES(NULL, 'KATIA RAQUEL', 'F', 'RAQUELKATIA@HOTMAIL.COM', '566247723');
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

-- INSERINDO DADOS NA TABELA ENDERECO
INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES(NULL, 'QE 11 AREA ESPECIAL C', 'GUARA I', 'BRASILIA', 'DF', 1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CRISTIANO OLSEN', 'JARDIM SUMARE', 'ARCATUBA', 'SP', 3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DA IMPRENSSA', 'MONTE CASTELO', 'CAMPO GRANDE', 'MS', 2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CARLOS AUGUSTO CORNELSEN', 'BOM RETIRO', 'CURITIBA', 'PR', 5);
INSERT INTO ENDERECO VALUES(NULL, 'AV. AFONSO PENA', 'BOA VIAGEM', 'B. HORIZONTE', 'MG', 6);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);


-- INSERINDO DADOS NA TABELA TELEFONE
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '123494567', 5);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '321659873', 5);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '456932156', 1);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '020145903', 2);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '302407085', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '741028536', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '852134697', 3);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '984630012', 1);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '000223665', 5);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '754855230', 2);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '68976565' , 9);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '99656675' , 9);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '33567765' , 11);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '88668786' , 11);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '55689654' , 11);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '88687979' , 12);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '88965676' , 13);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '89966809' , 15);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '88679978' , 16);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '99655768' , 17);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '89955665' , 18);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '77455786' , 19);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '89766554' , 19);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '77755785' , 20);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '44522578' , 20);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '44522578' , 21);


---------------------------------------------------REALIZANDO CONSULTAS NO BANCO---------------------------------------------------

-- BUSCANDO O RELATORIO GERAL DE TODOS OS CLIENTES 
DESC CLIENTE;
DESC ENDERECO;
DESC TELEFONE;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
       T.TIPO, T.NUMERO, 
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


-- BUSCANDO TELATORIO SOMENTE DE DADOS DOS HOMENS
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
       T.TIPO, T.NUMERO, 
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

-- BUSCANDO TELATORIO SOMENTE DE DADOS DAS MULHERES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
       T.TIPO, T.NUMERO, 
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

/*CORRIGINDO UM ERRO NO PREENCHIMENTO DO SEXO*/
SELECT * FROM CLIENTE
WHERE IDCLIENTE = 16;

UPDATE CLIENTE SET SEXO = 'M'
WHERE IDCLIENTE = 16;


-- QUANTIDADE DE HOMENS E MULHERES
SELECT COUNT(*) AS QUANTIDADE, SEXO 
FROM CLIENTE
GROUP BY SEXO 

